student/urls.py
from django.urls import path
from .views import index
from .views import add
from .views import edit,delete

app_name = 'student'
urlpatterns = [
    
    path('', index, name='index'),
    path('add', add, name='add'),
    path('edit/<str:pk>', edit, name='edit'),
    path('delete/<str:pk>', delete, name='delete'),
    
]

users/urls.py
from django.urls import path
from .views import index
from .views import add
from .views import edit


app_name = 'users'
urlpatterns = [
    
    path('', index, name='index'),
    path('add', add, name='add'),
    path('edit/<str:pk>/', edit, name='edit'),
    
]

website/urls.py
from django.contrib import admin
from django.urls import path,include
from student.views import index
from dashboard.views import index
from teacher.views import index
from users.views import index


urlpatterns = [
    path('admin/', admin.site.urls),
    path('student/', include('student.urls')),
    path('', include('dashboard.urls')),
    path('teacher/', include('teacher.urls')),
    path('users/', include('users.urls')),
    path('rapport/', include('rapport.urls')),
]

student/models.py
from django.db import models

# Create your models here.
class Students(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    date_of_birth = models.DateField(max_length=10)
    country = models.CharField(max_length=30)
    phone = models.CharField(max_length=10)
    scolarship = models.CharField(max_length=5)
    matricule = models.CharField(max_length=15)
    

student/forms.py
from django import forms

from .models import Students

class StudentForm(forms.Form):
    username = forms.CharField(required=False)
    password = forms.CharField()
    remember_me = forms.BooleanField()
    
class StudentsForm(forms.ModelForm):
    class Meta:
        model = Students
        fields = ['first_name','last_name','date_of_birth','country','phone','scolarship','matricule']

        widgets = {
            'date_of_birth': forms.DateInput(attrs={'type': 'date'}),
            'phone':forms.NumberInput(attrs={'type': 'number'}), 
        }

student/views.py
from django.shortcuts import render,redirect

from .models import Students

from .forms import StudentsForm





# Create your views here.

def index(request):
    students = Students.objects.all()
    total = Students.objects.count()
    return render(request, "student/index.html",{'students':students, 'total':total})

def edit(request, pk):
    student = Students.objects.get(id=pk)
    if request.method == "POST":
        student = Students.objects.get(id=pk)
        form =StudentsForm(request.POST, instance=student)
        if form.is_valid():
            form.save()
            return redirect('student:index')
    else:
        
        students = StudentsForm(instance=student)
        
        
        context = {'students':students}
        return render(request, "student/edit.html",context)

def add(request):
    if request.method == 'POST':
        form = StudentsForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('student:index')  # Redirect to users list after successful form submission.
        else:
            forms = StudentsForm()
            context= {'form':forms}
            context= {'error': "Invalid field submitted",'form':forms}
            return render(request, "student/add.html",context)
    else:
        forms = StudentsForm()
        context= {'form':forms}
        return render(request, "student/add.html",context)
    
def delete(request, pk):
    teacher = Students.objects.get(id=pk)
    teacher.delete()
    
    return redirect('student:index')
    

templates/student/add.html
{% extends "base.html" %} {% load crispy_forms_tags %} {% load static %}
{%block title %}Ajouter un élève{% endblock title %} {% block content %}
<!-- Main Content -->
<div class="flex-1 p-6">
  <a
    href="{% url 'student:index' %}"
    class="flex items-center mb-6 text-gray-500 hover:text-gray-700"
  >
    <svg
      xmlns="http://www.w3.org/2000/svg"
      class="w-5 h-5 mr-2"
      fill="none"
      viewBox="0 0 24 24"
      stroke="currentColor"
    >
      <path
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="2"
        d="M15 19l-7-7 7-7"
      />
    </svg>
    Retour
  </a>
  <div class="max-w-4xl p-8 mx-auto bg-white rounded-lg shadow-lg">
    <h1 class="mb-6 text-2xl font-semibold text-center">Ajouter un élève</h1>
    {{ error }}
    <form action="#" method="POST" class="grid grid-cols-2 gap-6">
      {% csrf_token %} {{ form | crispy }}
      <!-- Boutons -->
      <div class="flex justify-center col-span-2 space-x-4">
        <button
          type="reset"
          class="px-4 py-2 font-bold text-white bg-red-500 rounded hover:bg-red-600"
        >
          Annuler
        </button>
        <button
          type="submit"
          class="px-4 py-2 font-bold text-white bg-green-500 rounded hover:bg-green-600"
        >
          Enregistrer
        </button>
      </div>
    </form>
  </div>
</div>
{% endblock content %}

templates/student/edit.html
{% extends "base.html" %} {% load crispy_forms_tags %} {% load static %}
{%load tailwind_filters %} {% load crispy_forms_tags %} {%block title %} Editer
L'eleve{%endblock title %} {% block script %}<link
  href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css"
  rel="stylesheet"
/>{% endblock script %} {% block content %}<!-- Main Content -->
<div class="flex-1 p-6">
  <a
    href="{% url 'student:index' %}"
    class="flex items-center mb-6 text-gray-500 hover:text-gray-700"
  >
    <svg
      xmlns="http://www.w3.org/2000/svg"
      class="w-5 h-5 mr-2"
      fill="none"
      viewBox="0 0 24 24"
      stroke="currentColor"
    >
      <path
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="2"
        d="M15 19l-7-7 7-7"
      />
    </svg>
    Retour
  </a>
  <div class="max-w-4xl p-8 mx-auto bg-white rounded-lg shadow-lg">
    <h1 class="mb-6 text-2xl font-semibold text-center">Modifier un élève</h1>
    <form action="#" method="POST" class="grid grid-cols-2 gap-6">
      {% csrf_token %} {{ students | crispy }}
      <!-- Bouton Soumettre -->
      <div class="col-span-2">
        <button
          type="submit"
          class="w-full p-3 text-white bg-indigo-600 rounded-md shadow hover:bg-indigo-500"
        >
          Enregistrer les modifications
        </button>
      </div>
    </form>
  </div>
</div>
{% endblock content %}<!-- Main Content -->
<div class="flex-1 p-6">
  <a
    href="{% url 'student:index' %}"
    class="flex items-center mb-6 text-gray-500 hover:text-gray-700"
  >
    <svg
      xmlns="http://www.w3.org/2000/svg"
      class="w-5 h-5 mr-2"
      fill="none"
      viewBox="0 0 24 24"
      stroke="currentColor"
    >
      <path
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="2"
        d="M15 19l-7-7 7-7"
      />
    </svg>
    Retour
  </a>
  <div class="max-w-4xl p-8 mx-auto bg-white rounded-lg shadow-lg">
    <h1 class="mb-6 text-2xl font-semibold text-center">Modifier un élève</h1>
    <form action="#" method="POST" class="grid grid-cols-2 gap-6">
      <!-- Champ Nom -->
      <div>
        <span class="w-full border-2"> {{ form.username }} </span>

        {{ form.password }} {{ form.remember_me }} {{ form.remember_me }}
        <label for="nom" class="block text-sm font-medium text-gray-700"
          >Nom</label
        >
        <input
          type="text"
          id="nom"
          name="nom"
          placeholder="Nom Précédent"
          class="block w-full p-2 mt-1 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
        />
      </div>
      <!-- Champ Prénom -->
      <div>
        <label for="prenom" class="block text-sm font-medium text-gray-700"
          >Prénom</label
        >
        <input
          type="text"
          id="prenom"
          name="prenom"
          placeholder="Prénom Précédent"
          class="block w-full p-2 mt-1 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
        />
      </div>
      <!-- Champ Genre -->
      <div class="col-span-2">
        <label class="block text-sm font-medium text-gray-700">Genre</label>
        <div class="flex items-center mt-1">
          <input
            type="radio"
            id="homme"
            name="genre"
            value="homme"
            class="w-4 h-4 text-indigo-600 border-gray-300 focus:ring-indigo-500"
            checked
          />
          <label
            for="homme"
            class="block ml-3 text-sm font-medium text-gray-700"
            >Homme</label
          >
          <input
            type="radio"
            id="femme"
            name="genre"
            placeholder="femme"
            class="w-4 h-4 ml-6 text-indigo-600 border-gray-300 focus:ring-indigo-500"
          />
          <label
            for="femme"
            class="block ml-3 text-sm font-medium text-gray-700"
            >Femme</label
          >
        </div>
      </div>
      <!-- Champ Matricule -->
      <div>
        <label for="matricule" class="block text-sm font-medium text-gray-700"
          >Matricule</label
        >
        <input
          type="text"
          id="matricule"
          name="matricule"
          placeholder="Matricule Précédent"
          class="block w-full p-2 mt-1 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
        />
      </div>
      <!-- Champ Date de Naissance -->
      <div>
        <label
          for="date_naissance"
          class="block text-sm font-medium text-gray-700"
          >Date de naissance</label
        >
        <input
          type="date"
          id="date_naissance"
          name="date_naissance"
          placeholder="2000-01-01"
          class="block w-full p-2 mt-1 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
        />
      </div>
      <!-- Champ Classe -->
      <div>
        <label for="classe" class="block text-sm font-medium text-gray-700"
          >Classe</label
        >
        <select
          id="classe"
          name="classe"
          class="block w-full p-2 mt-1 bg-white border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
        >
          <option value="Tle" selected>Tle</option>
          <option value="1ère">1ère</option>
          <option value="2nd">2nd</option>
          <option value="3ème">3ème</option>
          <option value="4ème">4ème</option>
          <option value="5ème">5ème</option>
          <option value="6ème">6ème</option>
        </select>
      </div>
      <!-- Champ Téléphone -->
      <div>
        <label for="telephone" class="block text-sm font-medium text-gray-700"
          >Téléphone</label
        >
        <input
          type="text"
          id="telephone"
          name="telephone"
          placeholder="telephone"
          class="block w-full p-2 mt-1 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
        />
      </div>
      <!-- Champ Ville -->
      <div>
        <label for="ville" class="block text-sm font-medium text-gray-700"
          >Ville</label
        >
        <input
          type="text"
          id="ville"
          name="ville"
          placeholder="Ville"
          class="block w-full p-2 mt-1 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
        />
      </div>
      <!-- Bouton Soumettre -->
      <div class="col-span-2">
        <button
          type="submit"
          class="w-full p-3 text-white bg-indigo-600 rounded-md shadow hover:bg-indigo-500"
        >
          Enregistrer les modifications
        </button>
      </div>
    </form>
  </div>
</div>

templates/student/fold.html
{% extends "base.html" %} {% load tailwind_filters %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <link
      href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css"
      rel="stylesheet"
    />
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  </head>
  <body>
    {% block content %}
    <form class="justify-center mx-auto my-auto text-center" action="">
      {{ form | crispy }}
    </form>
    {% endblock content %}
  </body>
</html>

templates/student/index.html
{% extends "base.html" %} {% load static %} {% block title %} Listes des
eleves{% endblock %} {% block script %}
<script src="{% static 'js/student.js' %}" defer></script>
{% endblock %} {% block content %}

<div class="flex-1 p-6">
  <div class="flex items-center justify-between mb-6">
    <h1 class="text-2xl font-semibold">Élèves ({{ total }})</h1>
    <a
      href="{% url 'student:add' %}"
      class="flex items-center text-blue-500 hover:text-blue-700"
    >
      <svg
        xmlns="http://www.w3.org/2000/svg"
        class="w-5 h-5 mr-2"
        fill="none"
        viewBox="0 0 24 24"
        stroke="currentColor"
      >
        <path
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-width="2"
          d="M12 4v16m8-8H4"
        />
      </svg>
      Nouvel élève
    </a>
  </div>
  <div class="p-6 overflow-auto bg-white rounded-lg shadow">
    <table class="min-w-full divide-y divide-gray-200">
      <thead class="bg-gray-50">
        <tr>
          <th
            class="px-6 py-3 text-xs font-medium tracking-wider text-left text-gray-500 uppercase"
          >
            Nom
          </th>
          <th
            class="px-6 py-3 text-xs font-medium tracking-wider text-left text-gray-500 uppercase"
          >
            Prénom
          </th>
          {% comment %}
          <th
            class="px-6 py-3 text-xs font-medium tracking-wider text-left text-gray-500 uppercase"
          >
            Genre
          </th>
          {% endcomment %}
          <th
            class="px-6 py-3 text-xs font-medium tracking-wider text-left text-gray-500 uppercase"
          >
            Classe
          </th>
          <th
            class="px-6 py-3 text-xs font-medium tracking-wider text-left text-gray-500 uppercase"
          >
            Matricule
          </th>
          <th
            class="px-6 py-3 text-xs font-medium tracking-wider text-left text-gray-500 uppercase"
          >
            Âge
          </th>
          <th
            class="px-6 py-3 text-xs font-medium tracking-wider text-left text-gray-500 uppercase"
          >
            Téléphone
          </th>
          <th
            class="px-6 py-3 text-xs font-medium tracking-wider text-left text-gray-500 uppercase"
          >
            Ville/Pays
          </th>
          <th
            class="px-6 py-3 text-xs font-medium tracking-wider text-left text-gray-500 uppercase"
          >
            Actions
          </th>
        </tr>
      </thead>
      <tbody class="bg-white divide-y divide-gray-200">
        {% for student in students %}
        <tr>
          <td class="px-6 py-4 whitespace-nowrap">{{ student.first_name }}</td>
          <td class="px-6 py-4 whitespace-nowrap">{{ student.last_name }}</td>
          <td class="px-6 py-4 whitespace-nowrap">{{ student.scolarship }}</td>
          <td class="px-6 py-4 whitespace-nowrap">{{ student.matricule }}</td>
          <td class="px-6 py-4 whitespace-nowrap">
            {{ student.date_of_birth }}
          </td>
          <td class="px-6 py-4 whitespace-nowrap">{{ student.phone }}</td>
          <td class="px-6 py-4 whitespace-nowrap">{{ student.country }}</td>

          <td class="px-6 py-4 whitespace-nowrap">
            <a
              href="{% url 'student:edit' student.id %}"
              class="px-4 py-1 font-bold text-white bg-yellow-500 rounded hover:bg-yellow-600"
            >
              Modifier
            </a>
            <a
              class="px-4 py-1 ml-2 font-bold text-white bg-red-500 rounded hover:bg-red-600"
              href="#popup{{ student.id }}"
            >
              Supprimer
            </a>
          </td>
        </tr>

        <!-- Modal -->
        <div id="popup{{ student.id }}" class="overlay">
          <div class="popup">
            <h3 class="text-lg font-medium leading-6 text-gray-900">
              Confirmer la suppression
            </h3>
            <div class="py-3 mt-2 px-7">
              <p class="text-sm text-gray-500">
                Êtes-vous sûr de vouloir supprimer cet élément ? Cette action
                est irréversible.
              </p>
            </div>
            <a class="close" href="#">&times;</a>
            <div class="content">
              <div class="items-center px-4 py-3">
                <a
                  href="{% url 'student:delete' student.id %}"
                  class="px-4 py-2 font-bold text-white bg-red-500 rounded hover:bg-red-600"
                  onclick="deleteItem()"
                >
                  Supprimer
                </a>
                {% comment %}
                <button
                  id="confirmDelete"
                  class="px-4 py-2 font-bold text-white bg-red-500 rounded hover:bg-red-600"
                ></button>
                {% endcomment %}
                <button
                  id="cancelDelete"
                  class="px-4 py-2 ml-2 font-bold text-gray-800 bg-gray-300 rounded hover:bg-gray-400"
                  onclick="closeModal()"
                >
                  Annuler
                </button>
              </div>
            </div>
          </div>
        </div>

        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endblock %}