teacher/urls.py
from django.urls import path
from .views import index
from .views import add
from .views import edit,delete

app_name = 'teacher'
urlpatterns = [
    
    path('', index, name='index'),
    path('add', add, name='add'),
    path('edit/<str:pk>/', edit, name='edit'),
    path('delete/<str:pk>/', delete, name='delete'),
    
]

users/urls.py
from django.urls import path
from .views import index
from .views import add
from .views import edit


app_name = 'users'
urlpatterns = [
    
    path('', index, name='index'),
    path('add', add, name='add'),
    path('edit/<str:pk>/', edit, name='edit'),
    
]

website/urls.py
from django.contrib import admin
from django.urls import path,include
from student.views import index
from dashboard.views import index
from teacher.views import index
from users.views import index


urlpatterns = [
    path('admin/', admin.site.urls),
    path('student/', include('student.urls')),
    path('', include('dashboard.urls')),
    path('teacher/', include('teacher.urls')),
    path('users/', include('users.urls')),
    path('rapport/', include('rapport.urls')),
]

teacher/models.py
from django.db import models

# Create your models here.
class Teacher(models.Model):
    name = models.CharField(max_length=10)
    last_name = models.CharField(max_length=10)
    birth_date = models.DateField()
    
    disponibility = models.BooleanField()
    courses = models.CharField(max_length=15)
    number = models.CharField(max_length=10)
    country  = models.CharField(max_length=20)
    lesson = models.CharField(max_length=100)
    next_meet = models.CharField(max_length=100)

teacher/forms.py
from django import forms

from .models import Teacher

# # Create your forms here.
# class Teacher(forms.Form):
#     name = forms.CharField()
#     last_name = forms.CharField()
#     birth_date = forms.DateField()
#     gender = forms.CharField()
#     matricule = forms.CharField()
#     courses = forms.CharField()
#     number = forms.CharField()
#     ville = forms.CharField()


class TeacherForm(forms.ModelForm):
    class Meta:
        model = Teacher
        fields = ["name","last_name","birth_date","disponibility","courses","number","country","lesson","next_meet"]
        widgets = {
            'birth_date': forms.DateInput(attrs={'type': 'date'}),
            'disponibility': forms.CheckboxInput(),
            'number':forms.NumberInput(attrs={'type': 'number'}),
            
        }

teacher/views.py
from django.shortcuts import render,redirect

from .models import Teacher

from .forms import TeacherForm





# Create your views here.

def index(request):
    teachers = Teacher.objects.all()
    return render(request, "teacher/index.html",{'teachers':teachers})

def edit(request, pk):
    teacher = Teacher.objects.get(id=pk)
    if request.method == "POST":
        teacher = Teacher.objects.get(id=pk)
        form = TeacherForm(request.POST, instance=teacher)
        if form.is_valid():
            form.save()
            return redirect('teacher:index')
    else:
        
        teachers = TeacherForm(instance=teacher)
        
        
        context = {'teachers':teachers}
        return render(request, "teacher/edit.html",context)

def add(request):
    if request.method == 'POST':
        form = TeacherForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('teacher:index')  # Redirect to users list after successful form submission.
        else:
            forms = TeacherForm()
            context= {'form':forms}
            context= {'error': "Invalid field submitted",'form':forms}
            return render(request, "teacher/add.html",context)
    else:
        forms = TeacherForm()
        context= {'form':forms}
        return render(request, "teacher/add.html",context)
    
def delete(request, pk):
    teacher = Teacher.objects.get(id=pk)
    teacher.delete()
    
    return redirect('teacher:index')
    

templates/teacher/add.html
{% extends "base.html" %} {% load static %} {% load crispy_forms_tags %}
{%block content %}
<!-- Main Content -->
<div class="flex-1 p-6">
  <a
    href="{% url 'teacher:index' %}"
    class="flex items-center mb-6 text-gray-500 hover:text-gray-700"
  >
    <svg
      xmlns="http://www.w3.org/2000/svg"
      class="w-5 h-5 mr-2"
      fill="none"
      viewBox="0 0 24 24"
      stroke="currentColor"
    >
      <path
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="2"
        d="M15 19l-7-7 7-7"
      />
    </svg>
    Retour
  </a>
  <div class="max-w-4xl p-8 mx-auto mt-40 bg-white rounded-lg shadow-lg">
    <h1 class="mb-6 text-2xl font-semibold text-center text-red-700">
      {% if error %}{{ error }}{% endif %}
    </h1>
    <h1 class="mb-6 text-2xl font-semibold text-center">
      Ajouter un professeur
    </h1>
    <form action="#" method="POST" class="grid grid-cols-2 gap-6">
      {% csrf_token %} {{ form | crispy }}
      <!-- Boutons -->
      <div class="flex justify-center col-span-2 space-x-4">
        <button
          type="reset"
          class="px-4 py-2 font-bold text-white bg-red-500 rounded hover:bg-red-600"
        >
          Annuler
        </button>
        <button
          type="submit"
          class="px-4 py-2 font-bold text-white bg-green-500 rounded hover:bg-green-600"
        >
          Enregistrer
        </button>
      </div>
    </form>
  </div>
</div>
{% endblock content %}

templates/teacher/edit.html
{% extends "base.html" %}{% load crispy_forms_tags %} {% load static %}
{%block title %}Modifier le professeur{% endblock title %} {% block content %}<!-- Main Content -->
<div class="flex-1 p-6">
  <a
    href="{% url 'teacher:index' %}"
    class="flex items-center mb-6 text-gray-500 hover:text-gray-700"
  >
    <svg
      xmlns="http://www.w3.org/2000/svg"
      class="w-5 h-5 mr-2"
      fill="none"
      viewBox="0 0 24 24"
      stroke="currentColor"
    >
      <path
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="2"
        d="M15 19l-7-7 7-7"
      />
    </svg>
    Retour
  </a>
  <div class="max-w-4xl p-8 mx-auto bg-white rounded-lg shadow-lg">
    <h1 class="mb-6 text-2xl font-semibold text-center">
      Formulaire de modification (Professeur)
    </h1>
    <form action="#" method="POST" class="grid grid-cols-2 gap-6">
      <!-- Champ Nom -->
      {% csrf_token %} {{ teachers | crispy}}

      <!-- Boutons -->
      <div class="flex justify-center col-span-2 space-x-4">
        <button
          type="reset"
          class="px-4 py-2 font-bold text-white bg-red-500 rounded hover:bg-red-600"
        >
          Annuler
        </button>
        <button
          type="submit"
          class="px-4 py-2 font-bold text-white bg-green-500 rounded hover:bg-green-600"
        >
          Enregistrer
        </button>
      </div>
    </form>
  </div>
</div>
{% endblock content %}

templates/teacher/index.html
{% extends "base.html" %} {% load static %} {% block title %}Mon Etab -
Professeur{% endblock title %} {% block script %}
<script src="{% static 'js/teacher.js' %}" defer></script>
{% endblock script %} {% block content %}

<div class="flex-1 p-6">
  <div class="flex items-center justify-between mb-6">
    <h1 class="text-2xl font-semibold">Professeurs (2)</h1>
    <a
      href="{% url 'teacher:add' %}"
      class="flex items-center text-blue-500 hover:text-blue-700"
    >
      <svg
        xmlns="http://www.w3.org/2000/svg"
        class="w-5 h-5 mr-2"
        fill="none"
        viewBox="0 0 24 24"
        stroke="currentColor"
      >
        <path
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-width="2"
          d="M12 4v16m8-8H4"
        />
      </svg>
      Nouveau professeur
    </a>
  </div>
  <div class="p-6 overflow-auto bg-white rounded-lg shadow">
    <table class="min-w-full divide-y divide-gray-200">
      <thead class="bg-gray-50">
        <tr>
          <th
            class="px-6 py-3 text-xs font-medium tracking-wider text-left text-gray-500 uppercase"
          >
            Nom
          </th>
          <th
            class="px-6 py-3 text-xs font-medium tracking-wider text-left text-gray-500 uppercase"
          >
            Prénom
          </th>
          <th
            class="px-6 py-3 text-xs font-medium tracking-wider text-left text-gray-500 uppercase"
          >
            Date de naissance
          </th>
          <th
            class="px-6 py-3 text-xs font-medium tracking-wider text-left text-gray-500 uppercase"
          >
            Matière
          </th>
          <th
            class="px-6 py-3 text-xs font-medium tracking-wider text-left text-gray-500 uppercase"
          >
            Vacant
          </th>

          <th
            class="px-6 py-3 text-xs font-medium tracking-wider text-left text-gray-500 uppercase"
          >
            Prochaine reunion
          </th>

          <th
            class="px-6 py-3 text-xs font-medium tracking-wider text-left text-gray-500 uppercase"
          >
            Téléphone
          </th>
          <th
            class="px-6 py-3 text-xs font-medium tracking-wider text-left text-gray-500 uppercase"
          >
            Ville/Pays
          </th>
          <th
            class="px-6 py-3 text-xs font-medium tracking-wider text-left text-gray-500 uppercase"
          >
            Actions
          </th>
        </tr>
      </thead>
      <tbody class="bg-white divide-y divide-gray-200">
        {% for teacher in teachers %}
        <tr>
          <td class="px-6 py-4 whitespace-nowrap">{{ teacher.name }}</td>
          <td class="px-6 py-4 whitespace-nowrap">{{ teacher.last_name }}</td>
          <td class="px-6 py-4 whitespace-nowrap">{{ teacher.birth_date }}</td>
          <td class="px-6 py-4 whitespace-nowrap">{{ teacher.courses }}</td>
          <td class="px-6 py-4 whitespace-nowrap">
            {{ teacher.disponibility }}
          </td>
          <td class="px-6 py-4 whitespace-nowrap">{{ teacher.next_meet }}</td>

          <td class="px-6 py-4 whitespace-nowrap">{{ teacher.number }}</td>
          <td class="px-6 py-4 whitespace-nowrap">{{ teacher.country }}</td>
          <td class="px-6 py-4 whitespace-nowrap">
            <a
              href=" {% url 'teacher:edit' teacher.id %}"
              class="px-4 py-1 font-bold text-white bg-yellow-500 rounded hover:bg-yellow-600"
            >
              Modifier
            </a>

            <a
              class="px-4 py-1 ml-2 font-bold text-white bg-red-500 rounded hover:bg-red-600"
              href="#popup{{ teacher.id }}"
            >
              Supprimer
            </a>
          </td>
        </tr>
        <!-- Modal -->
        <div id="popup{{ teacher.id }}" class="overlay">
          <div class="popup">
            <h3 class="text-lg font-medium leading-6 text-gray-900">
              Confirmer la suppression
            </h3>
            <div class="py-3 mt-2 px-7">
              <p class="text-sm text-gray-500">
                Êtes-vous sûr de vouloir supprimer cet élément ? Cette action
                est irréversible.
              </p>
            </div>
            <a class="close" href="#">&times;</a>
            <div class="content">
              <div class="items-center px-4 py-3">
                <a
                  href="{% url 'teacher:delete' teacher.id %}"
                  class="px-4 py-2 font-bold text-white bg-red-500 rounded hover:bg-red-600"
                  onclick="deleteItem()"
                >
                  Supprimer
                </a>
                {% comment %}
                <button
                  id="confirmDelete"
                  class="px-4 py-2 font-bold text-white bg-red-500 rounded hover:bg-red-600"
                ></button>
                {% endcomment %}
                <button
                  id="cancelDelete"
                  class="px-4 py-2 ml-2 font-bold text-gray-800 bg-gray-300 rounded hover:bg-gray-400"
                  onclick="closeModal()"
                >
                  Annuler
                </button>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endblock content %}