dashboard/urls.py
from django.urls import path
from .views import index,login

app_name = 'dashboard'
urlpatterns = [
    
    path('home/', index, name='index'),
    path('', login, name='login')
]

rapport/urls.py
from django.urls import path
from .views import index
# from .views import add
# from .views import edit

app_name = 'rapport'
urlpatterns = [
    
    path('', index, name='index'),
    # path('add', add),
    # path('edit', edit),
    
]

student/urls.py
from django.urls import path
from .views import index
from .views import add
from .views import edit,delete

app_name = 'student'
urlpatterns = [
    
    path('', index, name='index'),
    path('add', add, name='add'),
    path('edit/<str:pk>', edit, name='edit'),
    path('delete/<str:pk>', delete, name='delete'),
    
]

teacher/urls.py
from django.urls import path
from .views import index
from .views import add
from .views import edit,delete

app_name = 'teacher'
urlpatterns = [
    
    path('', index, name='index'),
    path('add', add, name='add'),
    path('edit/<str:pk>/', edit, name='edit'),
    path('delete/<str:pk>/', delete, name='delete'),
    
]

users/urls.py
from django.urls import path
from .views import index
from .views import add
from .views import edit


app_name = 'users'
urlpatterns = [
    
    path('', index, name='index'),
    path('add', add, name='add'),
    path('edit/<str:pk>/', edit, name='edit'),
    
]

website/urls.py
from django.contrib import admin
from django.urls import path,include
from student.views import index
from dashboard.views import index
from teacher.views import index
from users.views import index


urlpatterns = [
    path('admin/', admin.site.urls),
    path('student/', include('student.urls')),
    path('', include('dashboard.urls')),
    path('teacher/', include('teacher.urls')),
    path('users/', include('users.urls')),
    path('rapport/', include('rapport.urls')),
]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.shortcuts import render



# Create your views here.

def index(request):
    return render(request, "dashboard/index.html")
    
    
def login(request):
    return render(request, "dashboard/login.html")
    

templates/dashboard/index.html
{% extends "base.html" %} {% load static %} {% block title %}Mon Etab - Tableau
de Bord{% endblock title %} {% block menu %}{% endblock menu %}
 {% block content%}
<script
  type="text/javascript"
  src="{% static 'js/dashboard.js' %}"
  defer
></script>
<div class="flex min-h-screen">
  <!-- Sidebar -->
  <aside class="flex flex-col justify-between w-64 text-white bg-gray-800">
    <div class="p-6">
      <div class="flex items-center justify-center mb-8">
        <img src="{% static "images/logo.png" %}" alt="logo du site"
        width="50px" height="50px" class="mr-3" />
        <h2 class="text-3xl font-semibold">Mon Etab</h2>
      </div>

      <nav>
        <ul>
          <li class="mb-4">
            <a
              href="{% url 'dashboard:index' %}"
              class="flex items-center font-medium text-blue-400 hover:text-gray-400"
            >
              <span class="mr-2">🏠</span> Tableau de bord
            </a>
          </li>
          <li class="mb-4">
            <a
              href="{% url 'student:index' %}"
              class="flex items-center hover:text-gray-400"
            >
              <span class="mr-2">👥</span> Élèves
            </a>
          </li>
          <li class="mb-4">
            <a
              href="{% url 'teacher:index' %}"
              class="flex items-center hover:text-blue-500"
            >
              <span class="mr-2">👩‍🏫</span> Professeurs
            </a>
          </li>
          <li class="mb-4">
            <a
              href="{% url 'users:index' %}"
              class="flex items-center hover:text-gray-400"
            >
              <span class="mr-2">👤</span> Utilisateurs
            </a>
          </li>
          <li class="mb-4">
            <a
              href="{% url 'rapport:index' %}"
              class="flex items-center hover:text-gray-400"
            >
              <span class="mr-2">📊</span> Rapport
            </a>
          </li>
        </ul>
      </nav>
    </div>
    <div class="p-6">
      <a
        href="#"
        class="flex items-center justify-center text-gray-400 hover:text-white"
      >
        <span class="mr-2">🔓</span> Déconnexion
      </a>
    </div>
  </aside>

  <!-- Main Content -->
  <div class="flex-1 p-6">
    <h1 class="mb-6 text-2xl font-semibold">Tableau de bord</h1>
    <div class="grid grid-cols-1 gap-6 md:grid-cols-2">
      <!-- Stat Box 1 -->
      <div class="p-6 bg-white rounded-lg shadow">
        <h3 class="mb-4 text-lg font-bold text-black">Nombre d'élève</h3>
        <p class="p-20 text-4xl font-bold text-center">128 100</p>
      </div>
      <!-- Stat Box 2 -->
      <div class="p-6 bg-white rounded-lg shadow">
        <h3 class="mb-4 text-lg font-bold text-black">Nombre de professeur</h3>
        <p class="p-20 text-4xl font-bold text-center">128 100</p>
      </div>
      <!-- Stat Box 3 -->
      <div class="p-6 bg-white rounded-lg shadow">
        <h3 class="mb-4 text-lg font-bold text-black">Nombre d'utilisateur</h3>
        <p class="p-20 text-4xl font-bold text-center">128 100</p>
      </div>
      <!-- Stat Box 4 (Pie Chart) -->
      <div class="flex flex-col items-center p-6 bg-white rounded-lg shadow">
        <h3 class="mb-4 text-lg font-bold text-left text-black">
          Élève par genre
        </h3>
        <div class="relative w-full h-64">
          <canvas id="pieChart"></canvas>
        </div>
        <div class="mt-4">
          <ul class="grid grid-cols-2 gap-2">
            <li class="flex items-center mb-2">
              <span class="inline-block w-4 h-4 mr-2 bg-blue-500"></span>
              Homme
            </li>
            <li class="flex items-center mb-2">
              <span class="inline-block w-4 h-4 mr-2 bg-red-500"></span>
              Femme
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/dashboard/login.html
{% extends "base.html" %} {% load static %} {% block menu %}{% endblock menu %} {% block title %}Page de
connexion{%endblock %} {% block content %}
<div class="flex flex-wrap justify-center w-screen h-screen bg-black">
  <div class="w-1/3 p-4 m-auto bg-gray-200 h-fit-content rounded-2xl">
    <div class="flex w-full my-20">
      <img
        class="ms-40"
        src="{% static  'images/logo.png' %}"
        alt="logo du site"
        width="100px"
        height="100px"
      />
      <h1 class="mt-5 text-6xl font-bold text-center">Mon Etab</h1>
    </div>
    <div class="grid w-full mx-auto text-xl font-bold text-center">
      <input
        class="w-[90%] mx-auto p-2 border-4 border-solid border-black placeholder:bold placeholder:text-black"
        type="text"
        class="form-control"
        placeholder="Identifiant"
      />
      <input
        class="w-[90%] mx-auto p-2 mt-5 border-4 border-solid border-black placeholder:bold placeholder:text-black"
        type="password"
        class="mt-4 form-control"
        placeholder="Mot de passe"
      />
      <button
        class="w-[90%] mx-auto shadow-2xl shadow-black my-10 bg-blue-500 text-white font-bold hover:bg-blue-700 p-4"
      >
        <a href="home">Connexion</a>
      </button>
    </div>
  </div>
</div>
{% endblock %}