users/urls.py
from django.urls import path
from .views import index
from .views import add
from .views import edit


app_name = 'users'
urlpatterns = [
    
    path('', index, name='index'),
    path('add', add, name='add'),
    path('edit/<str:pk>/', edit, name='edit'),
    
]

website/urls.py
from django.contrib import admin
from django.urls import path,include
from student.views import index
from dashboard.views import index
from teacher.views import index
from users.views import index


urlpatterns = [
    path('admin/', admin.site.urls),
    path('student/', include('student.urls')),
    path('', include('dashboard.urls')),
    path('teacher/', include('teacher.urls')),
    path('users/', include('users.urls')),
    path('rapport/', include('rapport.urls')),
]

users/models.py
from django.db import models

# Create your models here.
class User(models.Model):

    pseudos = models.CharField(max_length=10,unique=True,)
    password = models.CharField(max_length=120,null=True)
    creat_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.pseudos

users/forms.py
from django import forms
from .models import User
# Create your models here.
class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('pseudos', 'password')

users/views.py
from django.shortcuts import redirect, render

from .forms import UserForm

from .models import User


# Create your views here.

def index(request):
    user = User.objects.all()
    return render(request, "users/index.html",{'users':user})

def edit(request, pk):
    user = User.objects.get(id=pk)
    if request.method == "POST":
        form = UserForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            return redirect('users:index')
    else:
        
        form = UserForm(instance=user)
        
        
        context = {'form':form}
        return render(request, "users/edit.html",context)

def add(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('users:index')  # Redirect to users list after successful form submission.
    else:
        forms = UserForm()
        context= {'form':forms}
        return render(request, "users/add.html",context)
    

templates/users/add.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}Ajouter un Utilisateur{% endblock title %}
{% block content %}
<!-- Main Content -->
<div class="flex items-center justify-center flex-1 p-6">
   <div class="w-full max-w-md p-8 bg-white rounded-lg shadow-lg">
      <h1 class="mb-6 text-2xl font-semibold text-center">
         Ajouter un utilisateur
      </h1>
      <form action="#" method="POST" class="grid grid-cols-1 gap-6">
         {% csrf_token %}
         <!-- Champ  -->
        {{ form | crispy }}
         <!-- Boutons -->
         <div class="flex justify-center space-x-4">
            <button
               type="reset"
               class="px-4 py-2 font-bold text-white bg-red-500 rounded hover:bg-red-600"
            >
               Annuler
            </button>
            <button
               type="submit"
               class="px-4 py-2 font-bold text-white bg-green-500 rounded hover:bg-green-600"
            >
               Enregistrer
            </button>
         </div>
      </form>
   </div>
</div>
{% endblock content %}

templates/users/edit.html
{% extends "base.html" %} {% load static %} {% block title %}Ajouter un
Utilisateur{% endblock title %} {% block content %}
<!-- Main Content -->
<div class="flex items-center justify-center flex-1 p-6">
  <div class="w-full max-w-md p-8 bg-white rounded-lg shadow-lg">
    <h1 class="mb-6 text-2xl font-semibold text-center">
      Modifier un utilisateur
    </h1>
    <form action="" method="POST" class="grid grid-cols-1 gap-6">
      {% csrf_token %} {{form.as_p}}
      <button type="submit" class="btn btn-primary btn-sm" value="">
        Update
      </button>
    </form>
    <form action="#" method="POST" class="grid grid-cols-1 gap-6"></form>
  </div>
</div>
{% endblock content %}

templates/users/index.html
{% extends "base.html" %} {% load static %} {% block title %}Mon Etab -
utilisateurs{% endblock %} {% block content %}
<!-- Main Content -->
<div class="flex-1 p-6">
  <div class="flex items-center justify-between mb-6">
    <h1 class="text-2xl font-semibold">utilisateurs (2)</h1>
    <a
      href=" {% url 'users:add' %} "
      class="flex items-center text-blue-500 hover:text-blue-700"
    >
      <svg
        xmlns="http://www.w3.org/2000/svg"
        class="w-5 h-5 mr-2"
        fill="none"
        viewBox="0 0 24 24"
        stroke="currentColor"
      >
        <path
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-width="2"
          d="M12 4v16m8-8H4"
        />
      </svg>
      Nouvel utilisateurs
    </a>
  </div>
  <div class="p-6 overflow-auto bg-white rounded-lg shadow">
    <table class="min-w-full divide-y divide-gray-200">
      <thead class="bg-gray-50">
        <tr>
          <th
            class="px-6 py-3 text-xs font-medium tracking-wider text-left text-gray-500 uppercase"
          >
            Nom
          </th>
          <th
            class="px-6 py-3 text-xs font-medium tracking-wider text-left text-gray-500 uppercase"
          >
            date de creation
          </th>

          <th
            class="px-6 py-3 text-xs font-medium tracking-wider text-left text-gray-500 uppercase"
          >
            Actions
          </th>
        </tr>
      </thead>
      <tbody class="bg-white divide-y divide-gray-200">
        {% for user in users %}
        <tr>
          <td class="px-6 py-4 whitespace-nowrap">{{user.pseudos}}</td>
          <td class="px-6 py-4 whitespace-nowrap">{{user.creat_at}}</td>

          <td class="px-6 py-4 whitespace-nowrap">
            <a
              href=" {% url 'users:edit' user.id %} "
              class="px-4 py-1 font-bold text-white bg-yellow-500 rounded hover:bg-yellow-600"
            >
              Modifier
            </a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock content %}